#!/bin/sh

CACHE_DIR="$HOME/.cache"
CACHE_FILE="$CACHE_DIR/fuzzel-path"
PROGRAM_CACHE="$CACHE_DIR/fuzzel-program-cache"
PATH_HASH=$(echo $PATH | md5sum | awk '{print $1}')

# Check if the cache file exists and is up-to-date
if [ -f "$CACHE_FILE" ] && [ "$(cat "$CACHE_FILE")" = "$PATH_HASH" ]; then
    cat "$PROGRAM_CACHE" | fuzzel --dmenu
else
    # Regenerate the cache
    find $(echo $PATH | tr ':' ' ') -type f -executable | awk -F/ '{print $NF}' > "$PROGRAM_CACHE"
    echo "$PATH_HASH" > "$CACHE_FILE"
    cat "$PROGRAM_CACHE" | fuzzel --dmenu
fi
