server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "dmenu"
preview_length = 80
grpc_max_message_size = 8388608

[rofi]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []
show_source_prefix = false

[dmenu]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []
show_source_prefix = false

[fuzzel]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []
show_source_prefix = false

[choose]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []
show_source_prefix = false

[custom_finder]
program = "fzf"
args = []

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
